# Predicting Hypertension: Risikofaktorenanalyse mit NHANES-Daten

#### 1. Hintergrund und Ziel des Projekts:

Hypertonie, also Bluthochdruck, ist ein wichtiger Risikofaktor für Herz-Kreislauf-Erkrankungen. Da Bluthochdruck häufig lange unbemerkt bleibt, ist es aus Public-Health- und Data-Science-Sicht interessant zu untersuchen, welche individuellen Merkmale mit Hypertonie zusammenhängen und ob ein Machine-Learning-Modell den Hypertonie-Status einer Person anhand ausgewählter Risikofaktoren vorhersagen kann.

Die zentrale Fragestellung dieses Projektteils lautet:

**Kann ein Machine-Learning-Modell auf Basis von NHANES-Individualdaten vorhersagen, ob eine Person Hypertonie hat, und welche Risikofaktoren tragen am stärksten zur Vorhersage bei?**

Dabei soll nicht medizinisch diagnostiziert werden, ob eine Person tatsächlich Bluthochdruck hat. Das Ziel ist eine datenbasierte Klassifikation und explorative Analyse auf Basis öffentlich verfügbarer Gesundheitsdaten.

#### 2. Datenquelle

Für dieses Projekt werden Daten aus der National Health and Nutrition Examination Survey (NHANES) verwendet. NHANES ist eine US-amerikanische Gesundheitsstudie, die Interviewdaten, Untersuchungsdaten und Messwerte von Teilnehmenden enthält.

Ausgewählt wurde der Zyklus:

NHANES August 2021–August 2023

Dieser Zeitraum wurde gewählt, weil es sich um einen aktuellen, zusammenhängenden NHANES-Zyklus handelt und die relevanten Datendateien für Blutdruck, Demografie und Körpermaße öffentlich verfügbar sind.

Für den ersten Projektteil werden folgende NHANES-Dateien verwendet:


| **Datei**                 | **Inhalt**                                                                                  | **Rolle im Projekt**                                                                                 |
|-------------------------------|-----------------------------------------------------------------------------------------------|-----------------------------------------------------------------------------------------------|
| `BPQ_L`                   | Blood Pressure & Cholesterol Questionnaire  | Zielvariable Hypertonie.                |
| `DEMO_L`           | Demographic Variables and Sample Weights      | Features: Alter und Geschlecht        |
| `BMX_L`  | Body Measures            | Features: BMI und Taillenumfang

Die Datensätze werden über die gemeinsame Personen-ID SEQN zusammengeführt.


#### 3. Zielvariable / Target

Die Zielvariable beschreibt, ob eine Person Hypertonie hat oder nicht.

Als Target wird zunächst folgende Variable verwendet:

|Variable                 | Bedeutung                                                                                  | Nutzung im Projekt                                                                                 |
|-------------------------------|-----------------------------------------------------------------------------------------------|-----------------------------------------------------------------------------------------------|
| `BPQ020`                   | Ever told you had high blood pressure	|Target für Hypertonie ja/nein

Die Variable BPQ020 fragt, ob einer Person jemals von einem Arzt oder einer anderen medizinischen Fachperson gesagt wurde, dass sie Hypertonie bzw. Bluthochdruck hat.

**Wichtig:** Zur Definition des Hypertonie-Status wurden die Variablen BPQ020, BPQ030 und BPQ150 aus dem Datensatz BPQ_L geprüft. BPQ020 erfasst, ob einer Person jemals Bluthochdruck mitgeteilt wurde. `BPQ030` beschreibt eine wiederholte Mitteilung bei zwei oder mehr Arztbesuchen, während `BPQ150` die aktuelle Einnahme von Blutdruckmedikamenten abbildet.Aufgrund der deskriptiven Prüfung der fehlenden Werte wurden BPQ030 und BPQ150 nicht als Zielvariablen verwendet, da beide einen Missing-Anteil von etwa **65 %** aufwiesen. BPQ020 zeigte dagegen keine fehlenden Werte und wurde daher als binäre Zielvariable für das Klassifikationsmodell ausgewählt.

Für das Machine-Learning-Modell wird diese Variable später in eine binäre Zielvariable umgewandelt:

|Originalwert                | Bedeutung                                                                                  |ML-Codierung                                                                                 |
|-------------------------------|-----------------------------------------------------------------------------------------------|-----------------------------------------------------------------------------------------------|
| 1                   | Ja, Hypertonie wurde mitgeteilt	1	| 1
|2         | Nein, keine Hypertonie mitgeteilt | 0
|7, 9, fehlend | Refused / Don't know / Missing| wird als fehlend behandelt


#### 4. Ausgewählte Features
Die Features wurden ausgewählt, weil sie fachlich nach WHO (Quellenangabe ..... ? )mit Hypertonie in Verbindung stehen, im NHANES-Datensatz verfügbar sind und für ein Klassifikationsmodell gut nutzbar sind.


|Variable               | Bedeutung                                                                                  |Warum ausgewählt?                                                                                 |
|-------------------------------|-----------------------------------------------------------------------------------------------|-----------------------------------------------------------------------------------------------|
|RIDAGEYR                   | Alter in Jahren| Hypertonie tritt mit steigendem Alter häufiger auf
|RIAGENDR         | Geschlecht |Hypertonie-Risiko und Muster können sich zwischen Männern und Frauen unterscheiden
|BMXBMI | Body Mass Index in kg/m² |BMI ist ein wichtiger körperbezogener Risikofaktor
|BMXWAIST |Taillenumfang in cm | Bauchfett bzw. zentraler Körperfettanteil kann mit kardiometabolischem Risiko zusammenhängen

Körpergröß(BMXHT) und Körpergewicht (BMXWT) wurden beibehalten, da sie zur Rekonstruktion fehlender BMI-Werte genutzt werden können. Dadurch kann der Informationsverlust durch fehlende BMI-Angaben reduziert werden.

**For Me** Diese erste Feature-Auswahl ist bewusst begrenzt. Sie ermöglicht einen sauberen Einstieg in Data Cleaning, EDA und Machine Learning. Weitere Variablen wie Rauchen, Alkoholkonsum, körperliche Aktivität oder Ernährung können später ergänzt werden.

#### 5. Geplante Analyse

Die Analyse besteht aus mehreren Schritten:

- Einlesen der NHANES-Datensätze
- Auswahl relevanter Variablen
- Zusammenführen der Datensätze über SEQN
- Erstellung der Zielvariable hypertension
- Prüfung fehlender Werte und ungültiger Codes
- Explorative Datenanalyse
- Vorbereitung der Features für Machine Learning
- Training und Vergleich verschiedener Klassifikationsmodelle
- Bewertung der Modelle mit geeigneten Metriken
- Interpretation der wichtigsten Einflussvariablen

**Methodische Einordnung** 

Da die Daten aus einer Beobachtungsstudie stammen, können mit diesem Projekt keine kausalen Aussagen getroffen werden. Das bedeutet: Das Modell kann zeigen, welche Variablen im Datensatz mit Hypertonie zusammenhängen und zur Vorhersage beitragen. Es kann aber nicht beweisen, dass ein bestimmter Faktor Hypertonie verursacht.

Die Ergebnisse werden daher als explorative Risikofaktorenanalyse und Machine-Learning-Demo interpretiert.

#### 01. Daten laden

Im ersten Schritt werden die ausgewählten NHANES-Datensätze in Python eingelesen. Die Datensätze stammen aus unterschiedlichen Themenbereichen und enthalten Informationen, die für die Entwicklung einer ersten Version des Machine-Learning-Modells zur Hypertonie-Risikoeinschätzung relevant sind.

Dazu gehören Angaben zum Hypertonie-Status, demografische Merkmale, anthropometrische Messwerte sowie ausgewählte gesundheits- und lebensstilbezogene Variablen. Berücksichtigt werden unter anderem Alter, Geschlecht, Körpergewicht, Körpergröße, BMI, Taillenumfang, Raucherstatus, Alkoholkonsum, körperliche Aktivität, Sitzzeit, Diabetes, chronische Nierenerkrankung und erhöhter Cholesterinstatus.

Nach dem Einlesen wird überprüft, ob die Datensätze korrekt geladen wurden. Dazu werden die Anzahl der Beobachtungen und Variablen, die verfügbaren Spaltennamen sowie erste Zeilen der Datensätze kontrolliert. Dieser Schritt dient dazu, einen ersten Überblick über die Datenstruktur zu erhalten und sicherzustellen, dass die benötigten Variablen für die weitere Datenaufbereitung verfügbar sind.

In [230]:
# Pakete importieren
import pandas as pd
import numpy as np

In [231]:
df = pd.read_csv('nhanes_merged.csv')

### 1.2 Auswahl relevanter Variablen

In diesem Schritt wurden aus den einzelnen NHANES-Datensätzen die für die Hypertonie-Risikoeinschätzung relevanten Variablen ausgewählt. Dabei wurden demografische Merkmale, anthropometrische Messwerte, Lebensstilfaktoren sowie ausgewählte gesundheitsbezogene Angaben berücksichtigt, die als mögliche Risikofaktoren oder Einflussgrößen für Hypertonie relevant sind.

Die Auswahl der Variablen erfolgte zusätzlich im Hinblick auf die geplante Streamlit-Anwendung. Daher wurden vor allem Merkmale einbezogen, die für Nutzerinnen und Nutzer verständlich sind und ohne zusätzliche medizinische Untersuchungen angegeben werden können. Laborwerte, medizinische Spezialparameter sowie sensible soziodemografische Merkmale wurden bewusst nicht in den finalen Datensatz aufgenommen.

Die Personen-ID `SEQN` wurde in allen Datensätzen beibehalten, da sie als eindeutiger Schlüssel für das Zusammenführen der einzelnen Dateien diente.

In [232]:
df.head()

,SEQN,BPQ020,BPQ080,RIAGENDR,RIDAGEYR,DMDMARTZ,BMXWT,BMXHT,BMXBMI,BMXWAIST,PAD790Q,PAD810Q,PAD680,SMQ020,SMQ040,DIQ010,ALQ111,ALQ121,KIQ022
0,130378.0,1.0,2.0,1.0,43.0,1.0,86.9,179.5,27.0,98.3,3.000000e+00,3.000000e+00,360.0,1.0,3.0,2.0,NaN,NaN,2.0
1,130379.0,1.0,2.0,1.0,66.0,1.0,101.8,174.2,33.5,114.7,4.000000e+00,3.000000e+00,480.0,1.0,3.0,2.0,1.0,2.000000e+00,2.0
2,130380.0,2.0,1.0,2.0,44.0,1.0,69.4,152.9,29.7,93.5,1.000000e+00,5.397605e-79,240.0,2.0,NaN,1.0,1.0,1.000000e+01,2.0
3,130386.0,2.0,2.0,1.0,34.0,1.0,90.6,173.3,30.2,106.1,1.000000e+00,1.000000e+00,180.0,1.0,3.0,2.0,1.0,4.000000e+00,2.0
4,130387.0,1.0,1.0,2.0,68.0,3.0,103.5,155.9,42.6,122.0,5.397605e-79,5.397605e-79,1200.0,2.0,NaN,2.0,1.0,5.397605e-79,2.0

In [233]:
##Struktur des Dataframes
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 6064 entries, 0 to 6063
Data columns (total 19 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   SEQN      6064 non-null   float64
 1   BPQ020    6064 non-null   float64
 2   BPQ080    6064 non-null   float64
 3   RIAGENDR  6064 non-null   float64
 4   RIDAGEYR  6064 non-null   float64
 5   DMDMARTZ  6063 non-null   float64
 6   BMXWT     5983 non-null   float64
 7   BMXHT     5997 non-null   float64
 8   BMXBMI    5970 non-null   float64
 9   BMXWAIST  5762 non-null   float64
 10  PAD790Q   6060 non-null   float64
 11  PAD810Q   6059 non-null   float64
 12  PAD680    6060 non-null   float64
 13  SMQ020    6064 non-null   float64
 14  SMQ040    2509 non-null   float64
 15  DIQ010    6064 non-null   float64
 16  ALQ111    5236 non-null   float64
 17  ALQ121    4775 non-null   float64
 18  KIQ022    6064 non-null   float64
dtypes: float64(19)
memory usage: 900.3 KB

### 02 Data Cleaning – Prüfung und Bereinigung der Daten 
In diesem Schritt werden die Variablen verständlich umbenannt, die ursprünglichen NHANES-Kodierungen in analysierbare Kategorien umgewandelt und fehlende bzw. nicht interpretierbare Werte geprüft und behandelt. Ziel ist es, einen sauberen Datensatz für die deskriptive Analyse und das spätere Machine-Learning-Modell vorzubereiten.

### 2.1. Umbenennung der Variablen
Die ursprünglichen NHANES-Variablennamen werden durch verständlichere Namen ersetzt, damit die spätere Analyse und Interpretation einfacher nachvollziehbar ist.

In [234]:
df.columns

Index(['SEQN', 'BPQ020', 'BPQ080', 'RIAGENDR', 'RIDAGEYR', 'DMDMARTZ', 'BMXWT',
       'BMXHT', 'BMXBMI', 'BMXWAIST', 'PAD790Q', 'PAD810Q', 'PAD680', 'SMQ020',
       'SMQ040', 'DIQ010', 'ALQ111', 'ALQ121', 'KIQ022'],
      dtype='str')

In [235]:
# Spaltennamen umbennen

df = df.rename(columns={

    #Hypertonie
    "BPQ020": "hypertension",
     #persönliche Daten
    "RIAGENDR": "gender",
    "RIDAGEYR": "age",
    
    #Gesundheitsdaten
    "BMXWT" : "weight(kg)",
    "BMXHT" : "height(cm)",
    "BMXBMI": "bmi",
    "BMXWAIST": "waist_circumference(cm)",
    
    # Lebensstil --> körperliche Aktivität
    "PAD790Q": "Moderate-intensity_activities_frequency",  # Häufigkeit moderater körperlicher Aktivitäten in der Freizeit
    "PAD810Q": "high_intensity_activities_frequency",  # Häufigkeit körperlich anstrengender Aktivitäten; evtl. interessant zum Vergleichen
    "PAD680": "sedentary_time_per_day",  # Sitzzeit pro Tag

    # Lebensstil --> Alkoholkonsum
    "ALQ111": "ever_alcohol_use",  # Mindestens einmal Alkohol getrunken; evtl. ableiten aus der nächsten Variable
    "ALQ121": "alcohol_frequency",  # Wie oft haben Sie in den letzten 12 Monaten ungefähr irgendeine Art von alkoholischem Getränk getrunken?  

    # Lebensstil --> Rauchstatus
    "SMQ040": "current_smoking_status",  # Aktueller Raucher; hier würde ich nur Ja (täglich + manche Tage) oder Nein unterscheiden
    "SMQ020": "cigarettes_ever_in_life",  # Durchschnittliche Anzahl Zigaretten/Tag in den letzten 30 Tagen; interessant für App

    # Stoffwechselprobleme
    "BPQ080": "high_cholesterol",  # Erhöhter Cholesterinspiegel
    "DIQ010": "diabetes",  # Diabetes
    "KIQ022": "kidney_disease",  # Chronische Nierenerkrankung / schwache oder versagende Nieren

})

        #Alter
        #Geschlecht
        #BMI
        #Taillenumfang
        #Raucherstatus
        #Alkoholkonsum
        #körperliche Aktivität
        ##Sitzzeit pro sd. am tag
        #Diabetes
        #erhöhter Cholesterinspiegel

In [236]:

df = df.drop(columns=['DMDMARTZ'])

In [237]:
df.columns

Index(['SEQN', 'hypertension', 'high_cholesterol', 'gender', 'age',
       'weight(kg)', 'height(cm)', 'bmi', 'waist_circumference(cm)',
       'Moderate-intensity_activities_frequency',
       'high_intensity_activities_frequency', 'sedentary_time_per_day',
       'cigarettes_ever_in_life', 'current_smoking_status', 'diabetes',
       'ever_alcohol_use', 'alcohol_frequency', 'kidney_disease'],
      dtype='str')

### 2.2 Behandlung fehlender Werte durch variablenspezifische Imputationsstrategien

Fehlende Werte wurden abhängig vom Skalenniveau und der fachlichen Bedeutung der jeweiligen Variable behandelt. 
Für kategoriale Variablen wurde eine Modus-Imputation verwendet, bei der fehlende Werte durch den häufigsten beobachteten Wert ersetzt werden. 
Für metrische Variablen wie Gewicht, Körpergröße und BMI wurde eine Median-Imputation durchgeführt, da der Median robuster gegenüber Ausreißern ist als der Mittelwert.

Bei gesundheits- und lebensstilbezogenen Variablen wie Diabetes, Rauchen, Alkoholkonsum und körperlicher Aktivität wurde zunächst geprüft, ob eine Imputation fachlich sinnvoll ist oder ob fehlende Angaben als eigene Kategorie berücksichtigt werden sollten.

In [238]:
df

,SEQN,hypertension,high_cholesterol,gender,age,weight(kg),height(cm),bmi,waist_circumference(cm),Moderate-intensity_activities_frequency,high_intensity_activities_frequency,sedentary_time_per_day,cigarettes_ever_in_life,current_smoking_status,diabetes,ever_alcohol_use,alcohol_frequency,kidney_disease
0,130378.0,1.0,2.0,1.0,43.0,86.9,179.5,27.0,98.3,3.000000e+00,3.000000e+00,360.0,1.0,3.0,2.0,NaN,NaN,2.0
1,130379.0,1.0,2.0,1.0,66.0,101.8,174.2,33.5,114.7,4.000000e+00,3.000000e+00,480.0,1.0,3.0,2.0,1.0,2.000000e+00,2.0
2,130380.0,2.0,1.0,2.0,44.0,69.4,152.9,29.7,93.5,1.000000e+00,5.397605e-79,240.0,2.0,NaN,1.0,1.0,1.000000e+01,2.0
3,130386.0,2.0,2.0,1.0,34.0,90.6,173.3,30.2,106.1,1.000000e+00,1.000000e+00,180.0,1.0,3.0,2.0,1.0,4.000000e+00,2.0
4,130387.0,1.0,1.0,2.0,68.0,103.5,155.9,42.6,122.0,5.397605e-79,5.397605e-79,1200.0,2.0,NaN,2.0,1.0,5.397605e-79,2.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6059,142305.0,1.0,1.0,2.0,76.0,60.4,151.4,26.4,89.0,2.000000e+00,5.397605e-79,480.0,2.0,NaN,3.0,NaN,NaN,2.0
6060,142307.0,2.0,1.0,2.0,49.0,NaN,143.8,NaN,NaN,3.000000e+00,5.397605e-79,480.0,1.0,3.0,1.0,1.0,1.000000e+01,2.0
6061,142308.0,2.0,2.0,1.0,50.0,79.3,173.3,26.4,98.4,1.000000e+00,5.397605e-79,600.0,2.0,NaN,2.0,1.0,8.000000e+00,2.0
6062,142309.0,2.0,2.0,1.0,40.0,81.9,179.1,25.5,96.0,2.000000e+00,5.397605e-79,240.0,2.0,NaN,2.0,2.0,NaN,2.0
6063,142310.0,1.0,2.0,2.0,80.0,72.1,161.7,27.6,110.8,5.397605e-79,5.397605e-79,360.0,1.0,3.0,2.0,1.0,3.000000e+00,1.0

In [239]:
# Dupplikate-Checks
df[df.duplicated()] #keine Dupplikate vorhanden

Empty DataFrame
Columns: [SEQN, hypertension, high_cholesterol, gender, age, weight(kg), height(cm), bmi, waist_circumference(cm), Moderate-intensity_activities_frequency, high_intensity_activities_frequency, sedentary_time_per_day, cigarettes_ever_in_life, current_smoking_status, diabetes, ever_alcohol_use, alcohol_frequency, kidney_disease]
Index: []

In [240]:
missing_values = df.isna().sum()
missing_percent = df.isna().mean() * 100

missing_table = pd.DataFrame({
    "missing_values": missing_values,
    "missing_percent": missing_percent
}).sort_values(by="missing_percent", ascending=False)

missing_table

                                         missing_values  missing_percent
current_smoking_status                             3555        58.624670
alcohol_frequency                                  1289        21.256596
ever_alcohol_use                                    828        13.654354
waist_circumference(cm)                             302         4.980211
bmi                                                  94         1.550132
weight(kg)                                           81         1.335752
height(cm)                                           67         1.104881
high_intensity_activities_frequency                   5         0.082454
sedentary_time_per_day                                4         0.065963
Moderate-intensity_activities_frequency               4         0.065963
hypertension                                          0         0.000000
SEQN                                                  0         0.000000
age                                                   0         0.000000
high_cholesterol                                      0         0.000000
gender                                                0         0.000000
cigarettes_ever_in_life                               0         0.000000
diabetes                                              0         0.000000
kidney_disease                                        0         0.000000

### Behandlung fehlender Werte und Rekodierung beim Raucherstatus

Bei der Variable `current_smoking_status` lagen viele fehlende Werte vor. Diese wurden nicht direkt als zufällig fehlende Werte interpretiert, sondern im Zusammenhang mit der Fragebogenlogik betrachtet. Die Variable `current_smoking_status` beschreibt den aktuellen Raucherstatus und wird nur Personen gestellt, die zuvor bei `cigarettes_ever_in_life` angegeben haben, bereits mindestens 100 Zigaretten im Leben geraucht zu haben.

Um keinen großen Anteil der Beobachtungen zu verlieren, wurden die fehlenden Werte daher nicht pauschal gelöscht. Stattdessen wurde zusätzlich die Vorfrage `cigarettes_ever_in_life` berücksichtigt. Personen, die angaben, nie mindestens 100 Zigaretten im Leben geraucht zu haben, wurden als aktuell nicht rauchend klassifiziert.

Die Antwortkategorien `Every day` und `Some days` aus `current_smoking_status` wurden als aktuelles Rauchen zusammengefasst und mit `1` kodiert. Die Kategorie `Not at all` sowie Personen mit `cigarettes_ever_in_life = No` wurden als aktuell nicht rauchend interpretiert und mit `0` kodiert.

Auf dieser Grundlage wurde eine binäre Variable für den aktuellen Raucherstatus gebildet:

`1 = Ja, aktuell rauchend`
`0 = Nein, aktuell nicht rauchend`

In [241]:
# neue Spalte erstellen
df["current_smoker"] = np.nan

# Ja: raucht aktuell täglich oder an manchen Tagen
df.loc[df["current_smoking_status"].isin([1, 2]), "current_smoker"] = 1

# Nein: raucht aktuell gar nicht
df.loc[df["current_smoking_status"] == 3, "current_smoker"] = 0

# Nein: hat nie mindestens 100 Zigaretten im Leben geraucht
df.loc[df["cigarettes_ever_in_life"] == 2, "current_smoker"] = 0

In [242]:
df["current_smoker"].value_counts(dropna=False)

current_smoker
0.0    5142
1.0     915
NaN       7
Name: count, dtype: int64

In [243]:
# wenige fehlende Werte wurden gelöscht

df = df.dropna(subset=["current_smoker"])

### Behandlung fehlender Werte beim Alkoholkonsum 

#### Rekodierung des Alkoholkonsums

Die Variable `alcohol_use` wurde als ordinale Variable aus den Angaben zum bisherigen Alkoholkonsum und zur Konsumhäufigkeit in den letzten zwölf Monaten abgeleitet. Die Kategorien wurden numerisch kodiert, wobei höhere Werte eine häufigere Alkoholkonsumfrequenz abbilden. Fehlende Werte, die nach Berücksichtigung der Fragebogenlogik nicht eindeutig zugeordnet werden konnten, wurden mittels Median-Imputation ersetzt. Der Median wurde gewählt, da die Variable ordinal skaliert ist und dadurch eine robuste zentrale Kategorie zur Ersetzung fehlender Werte verwendet werden kann.

Zusätzlich wurde mit alcohol_use_label eine beschreibende Label-Variable erstellt, um die numerischen Kategorien leichter interpretieren und in der explorativen Analyse sowie in der späteren Anwendung verständlich darstellen zu können. Nicht eindeutig erklärbare fehlende Angaben wurden nach der Ableitung aus der Analyse ausgeschlossen.
Die neue Variable wurde wie folgt kodiert:

- 0 = no_alcohol
- 1 = yearly
- 2 = monthly
- 3 = weekly
- 4 = daily

Die Variable regular_alcohol_12m wurde im Rahmen des Feature Engineerings aus den NHANES-Variablen ever_alcohol_use und alcohol_frequency abgeleitet. Dabei wurde die Fragebogenlogik berücksichtigt. Personen ohne bisherigen Alkoholkonsum oder ohne Alkoholkonsum im letzten Jahr wurden als nicht regelmäßige Alkoholkonsumenten kodiert. Wöchentlicher und täglicher Alkoholkonsum wurden als regelmäßiger Alkoholkonsum definiert.

### Behandlung fehlender Werte beim Alkoholkonsum

#### Rekodierung des Alkoholkonsums

Die Variable `alcohol_use` wurde im Rahmen des Feature Engineerings aus den NHANES-Variablen `ever_alcohol_use` und `alcohol_frequency` abgeleitet. Dabei wurde die Fragebogenlogik berücksichtigt. Personen, die angaben, nie Alkohol konsumiert zu haben, sowie Personen ohne Alkoholkonsum im letzten Jahr wurden der Kategorie `no_alcohol` zugeordnet. Die übrigen Angaben zur Konsumhäufigkeit in den letzten zwölf Monaten wurden zu jährlichem, monatlichem, wöchentlichem und täglichem Alkoholkonsum zusammengefasst.

Die Variable `alcohol_use` wurde als ordinale Variable kodiert, wobei höhere Werte eine häufigere Alkoholkonsumfrequenz abbilden:

- 0 = no_alcohol
- 1 = yearly
- 2 = monthly
- 3 = weekly
- 4 = daily

Fehlende Werte, die nach Berücksichtigung der Fragebogenlogik nicht eindeutig zugeordnet werden konnten, wurden mittels Median-Imputation ersetzt. Der Median wurde gewählt, da `alcohol_use` ordinal skaliert ist und dadurch eine robuste zentrale Kategorie zur Ersetzung fehlender Werte verwendet werden kann.

Zusätzlich wurde mit `alcohol_use_label` eine beschreibende Label-Variable erstellt, um die numerischen Kategorien leichter interpretieren zu können.

Für die finale Modellierung wurde zusätzlich die binäre Variable `regular_alcohol_12m` abgeleitet. Dabei wurden wöchentlicher und täglicher Alkoholkonsum in den letzten zwölf Monaten als regelmäßiger Alkoholkonsum kodiert. Kein Alkoholkonsum, jährlicher oder monatlicher Alkoholkonsum wurden als kein regelmäßiger Alkoholkonsum zusammengefasst.

In [244]:
# Sicherstellen, dass die Variablen numerisch sind
df["ever_alcohol_use"] = pd.to_numeric(df["ever_alcohol_use"], errors="coerce")
df["alcohol_frequency"] = pd.to_numeric(df["alcohol_frequency"], errors="coerce")

# Sondercodes als Missing behandeln
df["ever_alcohol_use"] = df["ever_alcohol_use"].replace({
    7: np.nan,
    9: np.nan
})

df["alcohol_frequency"] = df["alcohol_frequency"].replace({
    77: np.nan,
    99: np.nan
})

# alcohol_frequency:
# 0 = Never in last year
# 1 = Every day
# 2 = Nearly every day
# 3 = 3 to 4 times a week
# 4 = 2 times a week
# 5 = Once a week
# 6 = 2 to 3 times a month
# 7 = Once a month
# 8 = 7 to 11 times in last year
# 9 = 3 to 6 times in last year
# 10 = 1 to 2 times in last year
# 77 = Refused
# 99 = Don't know

def create_alcohol_use(row):
    ever_alcohol_use = row["ever_alcohol_use"]
    alcohol_frequency = row["alcohol_frequency"]

    # Person hat nie Alkohol getrunken
    if ever_alcohol_use == 2:
        return 0

    # Person hat im letzten Jahr keinen Alkohol getrunken
    if alcohol_frequency == 0:
        return 0

    # Jährlicher Konsum
    if alcohol_frequency in [8, 9, 10]:
        return 1

    # Monatlicher Konsum
    if alcohol_frequency in [6, 7]:
        return 2

    # Wöchentlicher Konsum
    if alcohol_frequency in [3, 4, 5]:
        return 3

    # Täglicher Konsum
    if alcohol_frequency in [1, 2]:
        return 4

    # echte, nicht erklärbare Missing-Werte
    return np.nan


# Numerische Variable für die Modellierung
df["alcohol_use"] = df.apply(create_alcohol_use, axis=1)

# Lesbare Kategorie für Kontrolle, EDA und App
alcohol_label_map = {
    0: "no_alcohol",
    1: "yearly",
    2: "monthly",
    3: "weekly",
    4: "daily"
}

df["alcohol_use_label"] = df["alcohol_use"].map(alcohol_label_map)


# regular_alcohol_12m erstellen
# 0 = kein regelmäßiger Alkoholkonsum
# 1 = regelmäßiger Alkoholkonsum
#
# weekly und daily werden als regelmäßiger Alkoholkonsum definiert.

df["regular_alcohol_12m"] = np.where(
    df["alcohol_use"].isin([3, 4]), 1, 0
)

In [245]:
# Median berechnen
alcohol_median = df["alcohol_use"].median()
df["alcohol_use"] = df["alcohol_use"].fillna(alcohol_median)
df["alcohol_use"] = df["alcohol_use"].astype(int)

# alcohol_use_label nach der Imputation neu erstellen
df["alcohol_use_label"] = df["alcohol_use"].map(alcohol_label_map)

In [246]:
print("Median für alcohol_use:", alcohol_median)

print("\nVerteilung alcohol_use:")
print(df["alcohol_use"].value_counts(dropna=False).sort_index())

print("\nVerteilung alcohol_use_label:")
print(df["alcohol_use_label"].value_counts(dropna=False))

print("\nVerteilung regular_alcohol_12m:")
print(df["regular_alcohol_12m"].value_counts(dropna=False))

Median für alcohol_use: 2.0

Verteilung alcohol_use:
alcohol_use
0     459
1    1245
2    2547
3    1342
4     464
Name: count, dtype: int64

Verteilung alcohol_use_label:
alcohol_use_label
monthly       2547
weekly        1342
yearly        1245
daily          464
no_alcohol     459
Name: count, dtype: int64

Verteilung regular_alcohol_12m:
regular_alcohol_12m
0    4251
1    1806
Name: count, dtype: int64

In [247]:
df["regular_alcohol_12m"].value_counts(dropna=False).sort_index()

regular_alcohol_12m
0    4251
1    1806
Name: count, dtype: int64

### Behandlung fehlender Werte und Bildung der Variablen zur körperlichen Aktivität und Sitzzeit

Die Angaben zu moderater und intensiver Freizeitaktivität wurden zu einer gemeinsamen Aktivitätsvariable zusammengefasst. Ziel war es, die körperliche Aktivität vereinfacht und gut interpretierbar für die weitere Analyse und Modellierung abzubilden.

Werte größer als 0 wurden als vorhandene Aktivität interpretiert. Sehr kleine numerische Werte nahe 0 wurden als 0 behandelt. Personen ohne moderate ode r intensive Aktivität wurden als nicht aktiv klassifiziert. Personen mit moderater Aktivität, aber ohne intensive Aktivität, wurden als moderat aktiv eingestuft. Sobald intensive Aktivität angegeben wurde, wurde die Person der Kategorie intensiv aktiv zugeordnet.

Die neue Variable `activity_level_label`wurde wie folgt kodiert:

- 0 = nicht aktiv 
- 1 = moderat aktiv
- 2 = intensiv aktiv

Zusätzlich wurde aus der Variable zur täglichen Sitzzeit eine besser interpretierbare metrische Variable gebildet. Da die Sitzzeit in Minuten pro Tag angegeben ist, wurde sie durch 60 geteilt und dadurch in Stunden pro Tag umgerechnet.

Die neu gebildeten Variablen lauten:

`sitting_hours_per_day = Sitzzeit in Stunden pro Tag`

In [248]:

moderate_col = "Moderate-intensity_activities_frequency"
vigorous_col = "high_intensity_activities_frequency"

# sehr kleine Werte praktisch als 0 behandeln
df.loc[df[moderate_col] < 0.000001, moderate_col] = 0
df.loc[df[vigorous_col] < 0.000001, vigorous_col] = 0

# neue Variable erstellen
df["activity_level"] = 0

# moderat aktiv: moderate Aktivität vorhanden, aber keine intensive
df.loc[
    (df[moderate_col] > 0) & (df[vigorous_col] == 0),
    "activity_level"
] = 1

# intensiv aktiv: intensive Aktivität vorhanden
df.loc[
    df[vigorous_col] > 0,
    "activity_level"
] = 2

In [249]:
#Für EDA Bereich 
df["activity_level_label"] = df["activity_level"].map({
    0: "nicht aktiv",
    1: "moderat aktiv",
    2: "intensiv aktiv"
})

df["activity_level_label"].value_counts(dropna=False)

activity_level_label
intensiv aktiv    2706
moderat aktiv     2181
nicht aktiv       1170
Name: count, dtype: int64

#### Rekodirung der Variable Sitzzeit

In [250]:
# Sonderwerte als Missing setzen
df["sedentary_time_per_day"] = df["sedentary_time_per_day"].replace({
    7777: np.nan,
    9999: np.nan,
    77: np.nan,
    99: np.nan
})

# Sitzzeit von Minuten in Stunden umrechnen
df["sitting_hours_per_day"] = df["sedentary_time_per_day"] / 60

In [251]:
df["sitting_hours_per_day"].isna().sum()

np.int64(43)

In [252]:
df["sitting_hours_per_day"].value_counts(dropna=False).sort_index()

sitting_hours_per_day
8.996009e-81      4
1.666667e-02      2
3.333333e-02      1
6.666667e-02      1
8.333333e-02      3
1.000000e-01      2
1.166667e-01      1
1.666667e-01      1
2.000000e-01      2
2.500000e-01      9
3.333333e-01      6
4.166667e-01      1
5.000000e-01     38
5.833333e-01      1
6.666667e-01      5
7.500000e-01      1
8.333333e-01      1
1.000000e+00    188
1.166667e+00      1
1.333333e+00      1
1.500000e+00     39
2.000000e+00    545
2.500000e+00      8
3.000000e+00    671
3.333333e+00      2
3.500000e+00      3
4.000000e+00    852
4.166667e+00      1
4.500000e+00      1
5.000000e+00    663
5.500000e+00      1
6.000000e+00    726
7.000000e+00    232
8.000000e+00    665
9.000000e+00    174
1.000000e+01    521
1.100000e+01     65
1.200000e+01    344
1.300000e+01     39
1.400000e+01     78
1.500000e+01     34
1.600000e+01     46
1.700000e+01      8
1.800000e+01     11
1.900000e+01      2
2.000000e+01     11
2.100000e+01      1
2.200000e+01      1
2.300000e+01      1
NaN              43
Name: count, dtype: int64

Bei der Prüfung der Sitzzeit in Stunden pro Tag zeigten sich einzelne sehr niedrige Werte unter einer Stunde. Da eine tägliche Sitzzeit von wenigen Minuten im Alltag als unplausibel einzuschätzen ist, wurden Werte unter einer Stunde als fehlende Werte kodiert. Anschließend wurden die fehlenden Werte mithilfe einer Median-Imputation ersetzt.

In [253]:
# sehr kleine / unplausible Sitzzeiten unter 1 Stunde als Missing setzen
df.loc[df["sitting_hours_per_day"] < 1, "sitting_hours_per_day"] = np.nan

# fehlende Werte mit Median ersetzen
df["sitting_hours_per_day"] = df["sitting_hours_per_day"].fillna(
    df["sitting_hours_per_day"].median()
)

In [254]:
df["sitting_hours_per_day"].value_counts(dropna=False).sort_index()

sitting_hours_per_day
1.000000     188
1.166667       1
1.333333       1
1.500000      39
2.000000     545
2.500000       8
3.000000     671
3.333333       2
3.500000       3
4.000000     852
4.166667       1
4.500000       1
5.000000     785
5.500000       1
6.000000     726
7.000000     232
8.000000     665
9.000000     174
10.000000    521
11.000000     65
12.000000    344
13.000000     39
14.000000     78
15.000000     34
16.000000     46
17.000000      8
18.000000     11
19.000000      2
20.000000     11
21.000000      1
22.000000      1
23.000000      1
Name: count, dtype: int64

In [255]:
df["sitting_hours_per_day"].isna().sum()

np.int64(0)

In [256]:
df["sitting_hours_per_day"].describe()

count    6057.000000
mean        6.134775
std         3.433404
min         1.000000
25%         4.000000
50%         5.000000
75%         8.000000
max        23.000000
Name: sitting_hours_per_day, dtype: float64

### Behandlung fehlender Werte bei anthropometrischen Variablen

Die anthropometrischen Variablen Körpergewicht, Körpergröße, BMI und Taillenumfang wurden gemeinsam betrachtet. Da der BMI aus Körpergewicht und Körpergröße berechnet werden kann, wurden fehlende BMI-Werte zunächst anhand der vorhandenen Angaben zu Gewicht und Größe ergänzt. Die Körpergröße lag in Zentimetern vor und wurde für die Berechnung in Meter umgerechnet.

Falls nach dieser Ableitung weiterhin fehlende Werte in den anthropometrischen Variablen vorhanden waren, wurden diese mithilfe einer Median-Imputation ersetzt. Der Median wurde verwendet, da er im Vergleich zum Mittelwert robuster gegenüber Ausreißern ist.

Für die spätere Modellierung werden insbesondere BMI und Taillenumfang als zentrale anthropometrische Risikofaktoren berücksichtigt, da beide Merkmale in einem engen Zusammenhang mit Übergewicht, Adipositas und kardiometabolischem Risiko stehen.

In [257]:
df[["weight(kg)", "height(cm)", "bmi", "waist_circumference(cm)"]].isna().sum()

weight(kg)                  81
height(cm)                  67
bmi                         94
waist_circumference(cm)    302
dtype: int64

In [258]:
# fehlende werte bei bmi erstmal durch die Rechnung Gewicht / ((Größe_in_cm)/100) ** 2) beahndeln

df['bmi'] = df['bmi'].fillna(
    df['weight(kg)'] / ((df['height(cm)']//100) ** 2)
)

In [259]:
# Median-Imputation 

df['waist_circumference(cm)'] = df['waist_circumference(cm)'].fillna(df['waist_circumference(cm)'].median())
df['weight(kg)'] = df['weight(kg)'].fillna(df['weight(kg)'].median())
df['height(cm)'] = df['height(cm)'].fillna(df['height(cm)'].median())
df['bmi'] = df['bmi'].fillna(df['bmi'].median())

In [260]:
df[["weight(kg)", "height(cm)", "bmi", "waist_circumference(cm)"]].isna().sum()

weight(kg)                 0
height(cm)                 0
bmi                        0
waist_circumference(cm)    0
dtype: int64

#### Rekodierung von BMI:

Die Standard-Grenzwerte für Erwachsene, von der WHO seit 1995 verwendet und heute von praktisch jeder Gesundheitsbehörde übernommen, lauten: Untergewicht unter 18,5, Normalgewicht 18,5 bis 24,9, Übergewicht 25 bis 29,9 und Adipositas ab 30.

In [261]:
#BMI kategorisieren

df["bmi_category"] = pd.cut(
    df["bmi"],
    bins=[0, 18.5, 24.9, 29.9, 100],
    labels=["underweight", "normal_weight", "overweight", "obesity"],
    right=True
)

In [262]:
df['bmi_category'].value_counts().sort_index()

bmi_category
underweight        87
normal_weight    1510
overweight       2009
obesity          2451
Name: count, dtype: int64

#### Behandlung fehlender Werte und Rekodierung der Zielvariable:  Hypertonie 
NHANES-Codierung bei BPQ020 ist wie folgt:
1 = Yes
2 = No
7 = Refused
9 = Don't know

Für die Zielvariable wurde eine binäre Variable erstellt: 1 = Hypertonie, 0 = keine Hypertonie. Nicht interpretierbare Antworten wie "Refused" oder "Don't know" wurden zunächst nicht zugeordnet und erscheinen dadurch als fehlende Werte.

In [263]:
# Werte von Zielvariable anzeigen 
df["hypertension"].value_counts()

hypertension
2.0    3743
1.0    2310
9.0       4
Name: count, dtype: int64

In [264]:
# Sonderwerte erst als Missing setzen
df["hypertension"] = df["hypertension"].replace({
    7: np.nan,
    9: np.nan,
    77: np.nan,
    99: np.nan
})

# dann 1 = Ja, 2 = Nein umkodieren
df["hypertension"] = df["hypertension"].replace({
    1: 1,
    2: 0
})

In [265]:
df = df.dropna(subset=["hypertension"])
df = df.reset_index(drop=True)

In [266]:
df["hypertension"].value_counts(dropna=False).sort_index()

hypertension
0.0    3743
1.0    2310
Name: count, dtype: int64

Da bei der Zielvariable Hypertonie nur 4 fehlende Werte vorlagen, wurden diese Beobachtungen aus der weiteren Analyse ausgeschlossen. 
Aufgrund des sehr geringen Anteils fehlender Werte führt der Ausschluss zu keinem relevanten Datenverlust.

#### Rekodierung von Geschlecht

In [267]:
# Geschlecht umkodieren

df['gender'] = df['gender'].map({
    1 : 'Male',
    2 : 'Female'
})

df['gender'].value_counts(dropna= False)

gender
Female    3338
Male      2715
Name: count, dtype: int64

#### Kategorisierung von Altergruppen
Einige numerische Variablen können zusätzlich in Kategorien eingeteilt werden, um Gruppenvergleiche und deskriptive Auswertungen zu erleichtern.

Das Alter wurde in Altersgruppen kategorisiert: unter 20 Jahre, 20–29, 30–39, 40–49, 50–59 und 60 Jahre oder älter. Dadurch kann die Altersverteilung übersichtlicher beschrieben und der Zusammenhang zwischen Alter und Hypertonie besser untersucht werden.

In [268]:
df['age'].value_counts(dropna= False)
df["age"].value_counts().sort_index()

age
20.0     53
21.0     69
22.0     59
23.0     62
24.0     62
       ...
76.0     78
77.0     68
78.0     54
79.0     66
80.0    341
Name: count, Length: 61, dtype: int64

In [269]:
# Alter kategorisieren

df['age_category'] = pd.cut(
    df['age'],
    bins= [19, 29, 39, 49, 59, np.inf],
    labels=["20-29", "30-39", "40-49", "50-59", "60+"],
    right= True
)

In [270]:
df['age_category'].isna().sum()

np.int64(0)

In [271]:
df['age_category'].value_counts().sort_index()

age_category
20-29     651
30-39     904
40-49     798
50-59     932
60+      2768
Name: count, dtype: int64

#### Behandlugn restlichen fehlenden Werte von Variablen

In [272]:
# Chronische Nierenerkrankung 
df['kidney_disease'].value_counts(dropna= False).sort_index()

kidney_disease
1.0     231
2.0    5811
9.0      11
Name: count, dtype: int64

In [273]:
#  7 und 9 auf Missing setzen 
df["kidney_disease"] = df["kidney_disease"].replace({
    7: np.nan,
    9: np.nan
})

# dann 1 = Ja, 2 = Nein umkodieren
df["kidney_disease"] = df["kidney_disease"].replace({
    1: 1,
    2: 0
})

df["kidney_disease"].value_counts(dropna=False)

kidney_disease
0.0    5811
1.0     231
NaN      11
Name: count, dtype: int64

In [274]:

df = df.dropna(subset=["kidney_disease"])

In [275]:
df["diabetes"].value_counts(dropna=False)

diabetes
2.0    4957
1.0     865
3.0     220
Name: count, dtype: int64

In [276]:
#  7 und 9 auf Missing setzen 
df["diabetes"] = df["diabetes"].replace({
    3: np.nan,
    9: np.nan
})

# dann 1 = Ja, 2 = Nein umkodieren
df["diabetes"] = df["diabetes"].replace({
    1: 1,
    2: 0
})

df["diabetes"].value_counts(dropna=False)

diabetes
0.0    4957
1.0     865
NaN     220
Name: count, dtype: int64

In [277]:
#Imputatuin
df['diabetes'] = df['diabetes'].fillna(df['diabetes'].median())

In [278]:
#  7 und 9 auf Missing setzen 
df["high_cholesterol"] = df["high_cholesterol"].replace({
    7: np.nan,
    9: np.nan
})

# dann 1 = Ja, 2 = Nein umkodieren
df["high_cholesterol"] = df["high_cholesterol"].replace({
    1: 1,
    2: 0
})

df["high_cholesterol"].value_counts(dropna=False)

high_cholesterol
0.0    3517
1.0    2490
NaN      35
Name: count, dtype: int64

In [279]:
# entscheidende Variable für uns dann Imputieren 
df['high_cholesterol'] = df['high_cholesterol'].fillna(df['high_cholesterol'].median())

In [280]:
df['high_cholesterol'].value_counts().sort_index()

high_cholesterol
0.0    3552
1.0    2490
Name: count, dtype: int64

In [281]:
df.columns

Index(['SEQN', 'hypertension', 'high_cholesterol', 'gender', 'age',
       'weight(kg)', 'height(cm)', 'bmi', 'waist_circumference(cm)',
       'Moderate-intensity_activities_frequency',
       'high_intensity_activities_frequency', 'sedentary_time_per_day',
       'cigarettes_ever_in_life', 'current_smoking_status', 'diabetes',
       'ever_alcohol_use', 'alcohol_frequency', 'kidney_disease',
       'current_smoker', 'alcohol_use', 'alcohol_use_label',
       'regular_alcohol_12m', 'activity_level', 'activity_level_label',
       'sitting_hours_per_day', 'bmi_category', 'age_category'],
      dtype='str')

In [282]:
# Prüfung fehlender Werte, letzte Kontrolle 
missing_values = df.isna().sum()

missing_table = pd.DataFrame({
    "missing_values": missing_values
   
}).sort_values(by="missing_values", ascending=False)

missing_table

                                         missing_values
current_smoking_status                             3540
alcohol_frequency                                  1286
ever_alcohol_use                                    829
sedentary_time_per_day                               42
high_intensity_activities_frequency                   5
Moderate-intensity_activities_frequency               4
age                                                   0
high_cholesterol                                      0
hypertension                                          0
gender                                                0
SEQN                                                  0
bmi                                                   0
waist_circumference(cm)                               0
weight(kg)                                            0
height(cm)                                            0
diabetes                                              0
cigarettes_ever_in_life                               0
kidney_disease                                        0
current_smoker                                        0
alcohol_use                                           0
alcohol_use_label                                     0
regular_alcohol_12m                                   0
activity_level                                        0
activity_level_label                                  0
sitting_hours_per_day                                 0
bmi_category                                          0
age_category                                          0

In [284]:
# die ursprünglichen Hilfsvariablen löschen
cols_to_drop = [
    "alcohol_frequency",
    "ever_alcohol_use",
    "current_smoking_status",
    "cigarettes_ever_in_life",
    'alcohol_use_label',
    'alcohol_use',
    "Moderate-intensity_activities_frequency",
    "high_intensity_activities_frequency",
    "sedentary_time_per_day"
]

df = df.drop(columns=cols_to_drop)

In [287]:
df.shape

(6042, 18)

In [288]:

df.to_csv("nhanes_cleand.csv", index=False)