# Predicting Hypertension: Risikofaktorenanalyse mit NHANES-Daten

#### 1. Hintergrund und Ziel des Projekts:

Hypertonie, also Bluthochdruck, ist ein wichtiger Risikofaktor für Herz-Kreislauf-Erkrankungen. Da Bluthochdruck häufig lange unbemerkt bleibt, ist es aus Public-Health- und Data-Science-Sicht interessant zu untersuchen, welche individuellen Merkmale mit Hypertonie zusammenhängen und ob ein Machine-Learning-Modell den Hypertonie-Status einer Person anhand ausgewählter Risikofaktoren vorhersagen kann.

Die zentrale Fragestellung dieses Projektteils lautet:

**Kann ein Machine-Learning-Modell auf Basis von NHANES-Individualdaten vorhersagen, ob eine Person Hypertonie hat, und welche Risikofaktoren tragen am stärksten zur Vorhersage bei?**

Dabei soll nicht medizinisch diagnostiziert werden, ob eine Person tatsächlich Bluthochdruck hat. Das Ziel ist eine datenbasierte Klassifikation und explorative Analyse auf Basis öffentlich verfügbarer Gesundheitsdaten.

#### 2. Datenquelle

Für dieses Projekt werden Daten aus der National Health and Nutrition Examination Survey (NHANES) verwendet. NHANES ist eine US-amerikanische Gesundheitsstudie, die Interviewdaten, Untersuchungsdaten und Messwerte von Teilnehmenden enthält.

Ausgewählt wurde der Zyklus:

NHANES August 2021–August 2023

Dieser Zeitraum wurde gewählt, weil es sich um einen aktuellen, zusammenhängenden NHANES-Zyklus handelt und die relevanten Datendateien für Blutdruck, Demografie und Körpermaße öffentlich verfügbar sind.

Für den ersten Projektteil werden folgende NHANES-Dateien verwendet:


| **Datei**                 | **Inhalt**                                                                                  | **Rolle im Projekt**                                                                                 |
|-------------------------------|-----------------------------------------------------------------------------------------------|-----------------------------------------------------------------------------------------------|
| `BPQ_L`                   | Blood Pressure & Cholesterol Questionnaire  | Zielvariable Hypertonie.                |
| `DEMO_L`           | Demographic Variables and Sample Weights      | Features: Alter und Geschlecht        |
| `BMX_L`  | Body Measures            | Features: BMI und Taillenumfang

Die Datensätze werden über die gemeinsame Personen-ID SEQN zusammengeführt.


#### 3. Zielvariable / Target

Die Zielvariable beschreibt, ob eine Person Hypertonie hat oder nicht.

Als Target wird zunächst folgende Variable verwendet:

|Variable                 | Bedeutung                                                                                  | Nutzung im Projekt                                                                                 |
|-------------------------------|-----------------------------------------------------------------------------------------------|-----------------------------------------------------------------------------------------------|
| `BPQ020`                   | Ever told you had high blood pressure	|Target für Hypertonie ja/nein

Die Variable BPQ020 fragt, ob einer Person jemals von einem Arzt oder einer anderen medizinischen Fachperson gesagt wurde, dass sie Hypertonie bzw. Bluthochdruck hat.

**Wichtig:** Zur Definition des Hypertonie-Status wurden die Variablen BPQ020, BPQ030 und BPQ150 aus dem Datensatz BPQ_L geprüft. BPQ020 erfasst, ob einer Person jemals Bluthochdruck mitgeteilt wurde. `BPQ030` beschreibt eine wiederholte Mitteilung bei zwei oder mehr Arztbesuchen, während `BPQ150` die aktuelle Einnahme von Blutdruckmedikamenten abbildet.Aufgrund der deskriptiven Prüfung der fehlenden Werte wurden BPQ030 und BPQ150 nicht als Zielvariablen verwendet, da beide einen Missing-Anteil von etwa **65 %** aufwiesen. BPQ020 zeigte dagegen keine fehlenden Werte und wurde daher als binäre Zielvariable für das Klassifikationsmodell ausgewählt.

Für das Machine-Learning-Modell wird diese Variable später in eine binäre Zielvariable umgewandelt:

|Originalwert                | Bedeutung                                                                                  |ML-Codierung                                                                                 |
|-------------------------------|-----------------------------------------------------------------------------------------------|-----------------------------------------------------------------------------------------------|
| 1                   | Ja, Hypertonie wurde mitgeteilt	1	| 1
|2         | Nein, keine Hypertonie mitgeteilt | 0
|7, 9, fehlend | Refused / Don't know / Missing| wird als fehlend behandelt


#### 4. Ausgewählte Features
Die Features wurden ausgewählt, weil sie fachlich nach WHO (Quellenangabe ..... ? )mit Hypertonie in Verbindung stehen, im NHANES-Datensatz verfügbar sind und für ein Klassifikationsmodell gut nutzbar sind.


|Variable               | Bedeutung                                                                                  |Warum ausgewählt?                                                                                 |
|-------------------------------|-----------------------------------------------------------------------------------------------|-----------------------------------------------------------------------------------------------|
|RIDAGEYR                   | Alter in Jahren| Hypertonie tritt mit steigendem Alter häufiger auf
|RIAGENDR         | Geschlecht |Hypertonie-Risiko und Muster können sich zwischen Männern und Frauen unterscheiden
|BMXBMI | Body Mass Index in kg/m² |BMI ist ein wichtiger körperbezogener Risikofaktor
|BMXWAIST |Taillenumfang in cm | Bauchfett bzw. zentraler Körperfettanteil kann mit kardiometabolischem Risiko zusammenhängen

Körpergröß(BMXHT) und Körpergewicht (BMXWT) wurden beibehalten, da sie zur Rekonstruktion fehlender BMI-Werte genutzt werden können. Dadurch kann der Informationsverlust durch fehlende BMI-Angaben reduziert werden.

**For Me** Diese erste Feature-Auswahl ist bewusst begrenzt. Sie ermöglicht einen sauberen Einstieg in Data Cleaning, EDA und Machine Learning. Weitere Variablen wie Rauchen, Alkoholkonsum, körperliche Aktivität oder Ernährung können später ergänzt werden.

#### 5. Geplante Analyse

Die Analyse besteht aus mehreren Schritten:

- Einlesen der NHANES-Datensätze
- Auswahl relevanter Variablen
- Zusammenführen der Datensätze über SEQN
- Erstellung der Zielvariable hypertension
- Prüfung fehlender Werte und ungültiger Codes
- Explorative Datenanalyse
- Vorbereitung der Features für Machine Learning
- Training und Vergleich verschiedener Klassifikationsmodelle
- Bewertung der Modelle mit geeigneten Metriken
- Interpretation der wichtigsten Einflussvariablen

**Methodische Einordnung** 

Da die Daten aus einer Beobachtungsstudie stammen, können mit diesem Projekt keine kausalen Aussagen getroffen werden. Das bedeutet: Das Modell kann zeigen, welche Variablen im Datensatz mit Hypertonie zusammenhängen und zur Vorhersage beitragen. Es kann aber nicht beweisen, dass ein bestimmter Faktor Hypertonie verursacht.

Die Ergebnisse werden daher als explorative Risikofaktorenanalyse und Machine-Learning-Demo interpretiert.

#### 01. Daten laden

Im ersten Schritt werden die ausgewählten NHANES-Datensätze in Python eingelesen. Diese Datensätze enthalten die Informationen, die für die erste Version des Machine-Learning-Modells benötigt werden: Angaben zum Hypertonie-Status, demografische Merkmale und körperbezogene Messwerte. Dabei wird geprüft, wie viele Beobachtungen und Variablen enthalten sind, welche Spalten verfügbar sind und ob die Daten korrekt geladen wurden.

In [2]:
# Pakete importieren
import pandas as pd
import numpy as np

In [ ]:
# NHANES 2021-2023 XPT-Dateien direkt von der CDC-Webseite einlesen

bpq_url = "https://wwwn.cdc.gov/Nchs/Data/Nhanes/Public/2021/DataFiles/BPQ_L.xpt" #Blood Pressure and Cholesterol 
demo_url = "https://wwwn.cdc.gov/Nchs/Data/Nhanes/Public/2021/DataFiles/DEMO_L.xpt" #demographic
bmx_url = "https://wwwn.cdc.gov/Nchs/Data/Nhanes/Public/2021/DataFiles/BMX_L.xpt"  # body Measures 
paq_url = "https://wwwn.cdc.gov/Nchs/Data/Nhanes/Public/2021/DataFiles/PAQ_L.xpt" #physical activity
slq_url = "https://wwwn.cdc.gov/Nchs/Data/Nhanes/Public/2021/DataFiles/SLQ_L.xpt" #sleep
diq_url = "https://wwwn.cdc.gov/Nchs/Data/Nhanes/Public/2021/DataFiles/DIQ_L.xpt" #Diabetes
alq_url = "https://wwwn.cdc.gov/Nchs/Data/Nhanes/Public/2021/DataFiles/ALQ_L.xpt" #alcohol
smq_url = "https://wwwn.cdc.gov/Nchs/Data/Nhanes/Public/2021/DataFiles/SMQ_L.xpt" #smoking
kiq_url = "https://wwwn.cdc.gov/Nchs/Data/Nhanes/Public/2021/DataFiles/KIQ_U_L.xpt" # Kidney disease 
mdq_url = "https://wwwn.cdc.gov/Nchs/Data/Nhanes/Public/2021/DataFiles/MCQ_L.xpt" # medical condition ( lever and thyroid )

bpq_all = pd.read_sas(bpq_url, format="xport") # Hypertonie Daten
demo_all =pd.read_sas(demo_url, format= 'xport') #demographische Daten
bmx_all = pd.read_sas(bmx_url, format= 'xport') # Körpermaßen

In [4]:
# Erste Kontrolle über die Datenstruktur
print("BPQ:", bpq_all.shape)
print("DEMO:", demo_all.shape)
print("BMX:", bmx_all.shape)

display(bpq_all.head())
display(demo_all.head())
display(bmx_all.head())

BPQ: (8501, 6)
DEMO: (11933, 27)
BMX: (8860, 22)

       SEQN  BPQ020  BPQ030  BPQ150  BPQ080  BPQ101D
0  130378.0     1.0     1.0     1.0     2.0      2.0
1  130379.0     1.0     1.0     1.0     2.0      2.0
2  130380.0     2.0     NaN     NaN     1.0      1.0
3  130384.0     2.0     NaN     NaN     2.0      2.0
4  130385.0     2.0     NaN     NaN     2.0      2.0

,SEQN,SDDSRVYR,RIDSTATR,RIAGENDR,RIDAGEYR,RIDAGEMN,RIDRETH1,RIDRETH3,RIDEXMON,RIDEXAGM,...,DMDHRGND,DMDHRAGZ,DMDHREDZ,DMDHRMAZ,DMDHSEDZ,WTINT2YR,WTMEC2YR,SDMVSTRA,SDMVPSU,INDFMPIR
0,130378.0,12.0,2.0,1.0,43.0,NaN,5.0,6.0,2.0,NaN,...,NaN,NaN,NaN,NaN,NaN,50055.450807,54374.463898,173.0,2.0,5.00
1,130379.0,12.0,2.0,1.0,66.0,NaN,3.0,3.0,2.0,NaN,...,NaN,NaN,NaN,NaN,NaN,29087.450605,34084.721548,173.0,2.0,5.00
2,130380.0,12.0,2.0,2.0,44.0,NaN,2.0,2.0,1.0,NaN,...,NaN,NaN,NaN,NaN,NaN,80062.674301,81196.277992,174.0,1.0,1.41
3,130381.0,12.0,2.0,2.0,5.0,NaN,5.0,7.0,1.0,71.0,...,2.0,2.0,2.0,3.0,NaN,38807.268902,55698.607106,182.0,2.0,1.53
4,130382.0,12.0,2.0,1.0,2.0,NaN,3.0,3.0,2.0,34.0,...,2.0,2.0,3.0,1.0,2.0,30607.519774,36434.146346,182.0,2.0,3.60

,SEQN,BMDSTATS,BMXWT,BMIWT,BMXRECUM,BMIRECUM,BMXHEAD,BMIHEAD,BMXHT,BMIHT,...,BMXLEG,BMILEG,BMXARML,BMIARML,BMXARMC,BMIARMC,BMXWAIST,BMIWAIST,BMXHIP,BMIHIP
0,130378.0,1.0,86.9,NaN,NaN,NaN,NaN,NaN,179.5,NaN,...,42.8,NaN,42.0,NaN,35.7,NaN,98.3,NaN,102.9,NaN
1,130379.0,1.0,101.8,NaN,NaN,NaN,NaN,NaN,174.2,NaN,...,38.5,NaN,38.7,NaN,33.7,NaN,114.7,NaN,112.4,NaN
2,130380.0,1.0,69.4,NaN,NaN,NaN,NaN,NaN,152.9,NaN,...,38.5,NaN,35.5,NaN,36.3,NaN,93.5,NaN,98.0,NaN
3,130381.0,1.0,34.3,NaN,NaN,NaN,NaN,NaN,120.1,NaN,...,NaN,NaN,25.4,NaN,23.4,NaN,70.4,NaN,NaN,NaN
4,130382.0,3.0,13.6,NaN,NaN,1.0,NaN,NaN,NaN,1.0,...,NaN,NaN,NaN,1.0,NaN,1.0,NaN,1.0,NaN,NaN

### 1.2. Auswahl relevanter Variablen

Nach dem Einlesen werden nur die Variablen ausgewählt, die für die Fragestellung relevant sind. Dadurch wird der Datensatz übersichtlicher und die weitere Analyse gezielter. Für die Zielvariable wird aus dem Datensatz BPQ_L die Variable BPQ020 verwendet, da sie angibt, ob einer Person jemals mitgeteilt wurde, dass sie Bluthochdruck hat. Aus DEMO_L werden Alter und Geschlecht ausgewählt, da diese wichtige demografische Einflussfaktoren sind. Aus BMX_L werden BMI und Taillenumfang verwendet, weil sie körperbezogene Risikofaktoren für Hypertonie darstellen.

Die Auswahl der Variablen erfolgt somit nicht zufällig, sondern orientiert sich direkt an der Fragestellung: Es sollen Merkmale verwendet werden, die fachlich mit Hypertonie zusammenhängen und für ein Klassifikationsmodell geeignet sind.

In [ ]:
# Relevante Variablen auswählen
# Zielvariable & Features 'BPQ150', #cholesterol : BPQ080 nicht vergessen 

bpq = bpq_all[['SEQN', 'BPQ020']] # Hypertonie ja/nein  
demo = demo_all[['SEQN', 'RIAGENDR', 'RIDAGEYR']] # Alter und Geschlecht beibehalten 
bmx = bmx_all [['SEQN','BMXWT', 'BMXHT', 'BMXBMI', 'BMXWAIST']] # BMI und Tallienumfang (Waist-to-Hip Ratio ? ! viele fehelende werte  )

**Wichtig**

Die finale Feature-Auswahl wurde im Hinblick auf die geplante Streamlit-Anwendung getroffen. Ziel war es, ein nutzerfreundliches und niedrigschwellig anwendbares Modell zu entwickeln. Daher wurden vor allem Variablen berücksichtigt, die ohne medizinische Fachkenntnisse und ohne zusätzliche Laboruntersuchungen leicht angegeben werden können.

Klinische Laborwerte oder medizinische Spezialparameter wurden bewusst ausgeschlossen, da diese Angaben vielen Nutzerinnen und Nutzern im Alltag nicht bekannt sind und die praktische Anwendbarkeit der Anwendung einschränken würden. Auch sensible soziodemografische Merkmale wie ethnische Zugehörigkeit, Bildungsstand oder Einkommen wurden nicht in das finale Modell aufgenommen. Obwohl solche Merkmale in epidemiologischen Analysen mit der Hypertonieprävalenz assoziiert sein können, sind sie im Kontext einer nutzerorientierten Risikoeinschätzung ethisch und datenschutzbezogen kritisch zu bewerten.

Der Fokus lag stattdessen auf allgemein erfassbaren, gesundheitsbezogenen und lebensstilbezogenen Risikofaktoren, die für Nutzerinnen und Nutzer leicht verständlich und nachvollziehbar sind.

In [6]:
#fehlende werte bei Bmi kann durch Gewicht/Größe *2 behandelt werden 
#Rauchen / Bewegung und Alkohol wollen wir später holen

#### 1.3. Tabellen über SEQN zusammenführen

Nachdem die relevanten Variablen aus den einzelnen NHANES-Dateien ausgewählt wurden, werden die Datensätze über die gemeinsame Personen-ID SEQN zusammengeführt. `SEQN` ist die eindeutige Identifikationsnummer jeder teilnehmenden Person in NHANES. Dadurch können Informationen aus verschiedenen Dateien derselben Person korrekt miteinander verbunden werden.
Das Zusammenführen ist notwendig, weil die relevanten Informationen nicht in einer einzigen Datei gespeichert sind.
Für den Merge wird ein inner join verwendet. Das bedeutet, dass nur Personen im finalen Datensatz bleiben, die in allen ausgewählten Dateien vorhanden sind. Dadurch wird sichergestellt, dass für jede Person alle benötigten Informationen für die erste Analyse- und Modellversion verfügbar sind.

In [7]:
# Datensätze über SEQN zusammenführen

df = (
    bpq
    .merge(demo, how= 'inner', on= 'SEQN')
    .merge(bmx, how= 'inner', on= 'SEQN')
)

In [8]:
df.shape

(6615, 8)

In [9]:
df.head()

       SEQN  BPQ020  RIAGENDR  RIDAGEYR  BMXWT  BMXHT  BMXBMI  BMXWAIST
0  130378.0     1.0       1.0      43.0   86.9  179.5    27.0      98.3
1  130379.0     1.0       1.0      66.0  101.8  174.2    33.5     114.7
2  130380.0     2.0       2.0      44.0   69.4  152.9    29.7      93.5
3  130386.0     2.0       1.0      34.0   90.6  173.3    30.2     106.1
4  130387.0     1.0       2.0      68.0  103.5  155.9    42.6     122.0

In [10]:
##Struktur des Dataframes
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 6615 entries, 0 to 6614
Data columns (total 8 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   SEQN      6615 non-null   float64
 1   BPQ020    6615 non-null   float64
 2   RIAGENDR  6615 non-null   float64
 3   RIDAGEYR  6615 non-null   float64
 4   BMXWT     6525 non-null   float64
 5   BMXHT     6539 non-null   float64
 6   BMXBMI    6512 non-null   float64
 7   BMXWAIST  6287 non-null   float64
dtypes: float64(8)
memory usage: 413.6 KB

### 02 Data Cleaning – Prüfung und Bereinigung der Daten 
In diesem Schritt werden die Variablen verständlich umbenannt, die ursprünglichen NHANES-Kodierungen in analysierbare Kategorien umgewandelt und fehlende bzw. nicht interpretierbare Werte geprüft und behandelt. Ziel ist es, einen sauberen Datensatz für die deskriptive Analyse und das spätere Machine-Learning-Modell vorzubereiten.

### 2.1. Umbenennung der Variablen
Die ursprünglichen NHANES-Variablennamen werden durch verständlichere Namen ersetzt, damit die spätere Analyse und Interpretation einfacher nachvollziehbar ist.

In [11]:
df.columns

Index(['SEQN', 'BPQ020', 'RIAGENDR', 'RIDAGEYR', 'BMXWT', 'BMXHT', 'BMXBMI',
       'BMXWAIST'],
      dtype='str')

Die nächsten Fragen beziehen sich auf körperliche Aktivitäten wie Sport, Sport oder körperlich aktive Hobbys, die Sie in Ihrer Freizeit nachgehen können. Wir interessieren uns für zwei Arten von körperlicher Aktivität: moderate und intensive. Aktivitäten mit moderater Intensität führen zu moderaten Erhöhungen der Atmung oder Herzfrequenz, während intensive Aktivitäten starke Erhöhungen der Atmung oder Herzfrequenz verursachen. Wie oft {machst du/machst SP} moderatintensive Freizeitaktivitäten?

 limitatiton ( vielleicht hat jemand mit Alkohol aufgehört ) Alkoholkonsum in letzten 12 Monaten ja nein erstmal danmn bei ja   ist schwierig deswegen haben wir wie was dein Alkohol konsum verhalten in letzten 12 Monaten genommen: ALQ121 --<> Wie oft haben Sie in den letzten 12 Monaten ungefähr irgendeine Art von alkoholischem Getränk getrunken? PROBE: Mit anderen Worten, wie viele Tage pro Woche, pro Monat oder pro Jahr haben Sie getrunken?

In [ ]:
# Spaltennamen umbennen

df = df.rename(columns={
    "SEQN": "pat_id",
    #Hypertonie
    "BPQ020": "hypertension",
     #persönliche Daten ( Ethnie ausschließen )
    "RIAGENDR": "gender",
    "RIDAGEYR": "age",
    'DMDMARTZ': 'Marital status'# Familienstand # (nur married/with Partner odr nein )

    #Gesundheitsdaten
    "BMXWT" : "weight(kg)",
    "BMXHT" : "height(cm)",
    "BMXBMI": "bmi",
    "BMXWAIST": "waist_circumference(cm)"

    #Lebensstil --> #Ernährungsgewöhnheiten
    # DR1TSODI  Natriumaufnahme (sehr höhe methodischer Aufwand) (das Verhältnis von Natrium zu Kalium--> Hohe Natriumaufnahme und niedrige Kaliumaufnahme passen fachlich gut zum Hypertonie-Risiko.)
    #DR1TPOTA  Kaliumaufnahme
    #DR1TKCAL  Energieaufnahme
    
    # Lebensstil --> körperliche Aktivität
    "PAD790Q": "Moderate-intensity_activities_frequency",  # Häufigkeit moderater körperlicher Aktivitäten in der Freizeit
    "PAD810Q": "high_intensity_activities_frequency",  # Häufigkeit körperlich anstrengender Aktivitäten; evtl. interessant zum Vergleichen
    "PAD680": "sedentary_time_per_day",  # Sitzzeit pro Tag

    # Lebensstil --> Schlafdauer? / Schlafstörung
    "DPQ030": "sleep_problems",  # Schlafprobleme oder zu viel Schlaf; wir nehmen nur Ja/Nein, interessant für App

    # Lebensstil --> Alkoholkonsum
    "ALQ111": "ever_alcohol_use",  # Mindestens einmal Alkohol getrunken; evtl. ableiten aus der nächsten Variable
    "ALQ121": "alcohol_frequency",  # Wie oft haben Sie in den letzten 12 Monaten ungefähr irgendeine Art von alkoholischem Getränk getrunken?  

    # Lebensstil --> Rauchstatus
    "SMQ040": "current_smoking_status",  # Aktueller Raucher; hier würde ich nur Ja (täglich + manche Tage) oder Nein unterscheiden
    "SMD650": "cigarettes_per_day_30d",  # Durchschnittliche Anzahl Zigaretten/Tag in den letzten 30 Tagen; interessant für App

    # Vorerkrankungen
    # Herzinfarkt und Schlaganfall ausschließen, weil sie mögliche Folgen von Hypertonie sein können

    # Stoffwechselprobleme
    "BPQ080": "high_cholesterol",  # Erhöhter Cholesterinspiegel
    "DIQ010": "diabetes",  # Diabetes
    "MCQ500": "liver_disease",  # Lebererkrankung; verschiedene Arten / Ja oder Nein
    "MCQ160M": "thyroid_problem",  # Schilddrüsenprobleme
    "KIQ022": "kidney_disease",  # Chronische Nierenerkrankung / schwache oder versagende Nieren


})

 #Alter
#Geschlecht
#BMI
#Taillenumfang
#Raucherstatus
#Alkoholkonsum
#körperliche Aktivität
##Sitzzeit
#Schlafdauer
#Diabetes
#erhöhter Cholesterinspiegel

In [ ]:
# erstmal fehlende Werten weil du musst dich entscheiden was du behlaten willst

**Feature Engineering** 

Numerische Features transformieren

### 2.2 Rekodierung der Variable
NHANES-Codierung bei BPQ020 ist wie folgt:
1 = Yes
2 = No
7 = Refused
9 = Don't know

Für die Zielvariable wurde eine binäre Variable erstellt: 1 = Hypertonie, 0 = keine Hypertonie. Nicht interpretierbare Antworten wie "Refused" oder "Don't know" wurden zunächst nicht zugeordnet und erscheinen dadurch als fehlende Werte.

In [13]:
# Werte von Zielvariable anzeigen 
df["hypertension"].value_counts()

hypertension
2.0    4278
1.0    2333
9.0       4
Name: count, dtype: int64

In [14]:
#Werte von Target-Variable umkodieren 

df['hypertension'] = df['hypertension'].map({
    1 : 1 ,
    2: 0  
})
# zur Kontrollel nochmal anzeigen 
df["hypertension"].value_counts(dropna= False)

hypertension
0.0    4278
1.0    2333
NaN       4
Name: count, dtype: int64

In [15]:
# Geschlecht umkodieren

df['gender'] = df['gender'].map({
    1 : 'Male',
    2 : 'Female'
})

df['gender'].value_counts(dropna= False)

gender
Female    3625
Male      2990
Name: count, dtype: int64

### 2.3 Kategorisierung ausgewählter Variablen
Einige numerische Variablen können zusätzlich in Kategorien eingeteilt werden, um Gruppenvergleiche und deskriptive Auswertungen zu erleichtern.

Das Alter wurde in Altersgruppen kategorisiert: unter 20 Jahre, 20–29, 30–39, 40–49, 50–59 und 60 Jahre oder älter. Dadurch kann die Altersverteilung übersichtlicher beschrieben und der Zusammenhang zwischen Alter und Hypertonie besser untersucht werden.

In [16]:
df['age'].value_counts(dropna= False)
#df["age"].value_counts().sort_index()

age
80.0    342
68.0    164
62.0    158
61.0    157
60.0    157
       ...
23.0     62
26.0     61
22.0     59
78.0     54
20.0     53
Name: count, Length: 65, dtype: int64

In [17]:
# Alter kategorisieren

df['age_category'] = pd.cut(
    df['age'],
    bins= [15, 19, 29, 39, 49, 59, 80],
    labels=["<20", "20-29", "30-39", "40-49", "50-59", "60+"],
    right= True
)

In [18]:
df['age_category'].value_counts().sort_index()

age_category
<20       551
20-29     654
30-39     905
40-49     800
50-59     933
60+      2772
Name: count, dtype: int64

#### Die vier WHO-Kategorien im Überblick
Die Standard-Grenzwerte für Erwachsene, von der WHO seit 1995 verwendet und heute von praktisch jeder Gesundheitsbehörde übernommen, lauten: Untergewicht unter 18,5, Normalgewicht 18,5 bis 24,9, Übergewicht 25 bis 29,9 und Adipositas ab 30.

In [19]:
#BMI kategorisieren

df["bmi_category"] = pd.cut(
    df["bmi"],
    bins=[0, 18.5, 24.9, 29.9, 100],
    labels=["underweight", "normal_weight", "overweight", "obesity"],
    right=True
)

In [20]:
df['bmi_category'].value_counts().sort_index()

bmi_category
underweight       149
normal_weight    1766
overweight       2024
obesity          2573
Name: count, dtype: int64

In [21]:
df.to_csv("nhanes_merged.csv", index=False)

#### 2.4 Prüfung fehlender Werte
Nach der Rekodierung wird geprüft, welche Variablen fehlende Werte enthalten und wie hoch der Anteil fehlender Werte ist.

In [22]:
missing_values = df.isna().sum()
missing_percent = df.isna().mean() * 100

missing_table = pd.DataFrame({
    "missing_values": missing_values,
    "missing_percent": missing_percent
}).sort_values(by="missing_percent", ascending=False)

missing_table
# Taillienumfang hat der höchsten anteil an fehlenden Werten

                         missing_values  missing_percent
waist_circumference(cm)             328         4.958428
bmi                                 103         1.557067
bmi_category                        103         1.557067
weight(kg)                           90         1.360544
height(cm)                           76         1.148904
hypertension                          4         0.060469
pat_id                                0         0.000000
age                                   0         0.000000
gender                                0         0.000000
age_category                          0         0.000000

In [23]:
# Dupplikate-Checks
df[df.duplicated()] #keine Dupplikate vorhanden

Empty DataFrame
Columns: [pat_id, hypertension, gender, age, weight(kg), height(cm), bmi, waist_circumference(cm), age_category, bmi_category]
Index: []

#### 2.5 Behandlung fehlender Werte
Der Umgang mit fehlenden Werten hängt von der betroffenen Variable und vom Anteil fehlender Werte ab. Für die Zielvariable werden fehlende Werte ausgeschlossen, da diese Personen nicht eindeutig einer Hypertonie-Gruppe zugeordnet werden können.

Nach der Rekonstruktion fehlender BMI-Werte wurden Fälle mit weiterhin fehlenden Werten in zentralen Analysevariablen entfernt. Eine Median-Imputation wurde nicht verwendet, da sie künstliche Durchschnittswerte erzeugen kann und individuelle Unterschiede nicht berücksichtigt. Aufgrund des geringen Anteils fehlender Werte wurde eine vollständige Fallanalyse gewählt.

In [24]:
# fehlende Werte von Zielvariable löschen 
df['hypertension'].value_counts(dropna= False)
df = df.dropna(subset= 'hypertension')

# fehlende werte bei bmi erstmal durch die Rechnung Gewicht / ((Größe_in_cm)/100) ** 2) beahndeln dann denn restlichen Na-Werte löschen 
# Fehlende BMI-Werte wurden nicht durch den Median ersetzt, sondern aus Körpergröße und Gewicht rekonstruiert, sofern diese Informationen vorhanden waren. 

df['bmi'] = df['bmi'].fillna(
    df['weight(kg)'] / ((df['height(cm)']//100) ** 2)
)

df = df.dropna(subset= ['bmi', 'weight(kg)', 'height(cm)', 'waist_circumference(cm)'] )

#Eine Median-Imputation wurde nicht gewählt, weil sie allen fehlenden Personen denselben künstlichen Durchschnittswert zuweisen würde.
#Bei medizinischen Variablen wie BMI kann dies die Verteilung und den Zusammenhang mit Hypertonie verzerren.

In [25]:
df.isna().sum()

pat_id                     0
hypertension               0
gender                     0
age                        0
weight(kg)                 0
height(cm)                 0
bmi                        0
waist_circumference(cm)    0
age_category               0
bmi_category               0
dtype: int64

In [26]:
df.shape

(6266, 10)

In [27]:
#df.to_csv("D:/Weiterbildung_DSI/My_Project/outputs/nhanes_cleand.csv", index= False)

df.to_csv("nhanes_cleand.csv", index=False)